version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3
    steps:
      - checkout
      - run:
          command: |
            git clone -b master git@github.com:stackstorm-exchange/ci.git ~/ci
            ~/ci/.circle/dependencies
     - save_cache:
        key: dependency-cache
        paths:
          - ~/.cache/pip
          - ~/ci
          - ~/.apt-cache

  test:
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3
    steps:
      - restore_cache:
         key: dependency-cache
      - run: ~/ci/.circle/test
     - save_cache:
        key: dependency-cache
        paths:
          - ~/.cache/pip
          - ~/ci
          - ~/.apt-cache
  deploy:
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3
    steps:
      - restore_cache:
         key: dependency-cache
      - checkout
      - run: ~/ci/.circle/deployment

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
