version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: mongo:3.4
      - image: rabbitmq:3
    steps:
      - checkout
      - run: git clone -b master git@github.com:stackstorm-exchange/ci.git ~/ci
      - run: ~/ci/.circle/dependencies
      - run: ~/ci/.circle/test
      - save_cache:
         key: dependency-cache
         paths:
           - ~/.cache/pip
           - virtualenv/
           - ~/ci
  deploy:
    docker:
      - image: circleci/python:2.7
      - image: mongo:3.4
      - image: rabbitmq:3
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache
      - run: ~/ci/.circle/deployment

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        filters:
          branches:
            only: master
